custom: ${file(config.yml)}
service: ${self:custom.account_name}-${self:custom.project}

provider:
  name: aws
  runtime: python3.7
  region: ${self:custom.region}
  stage: ${self:custom.env}
  deploymentBucket:
    name: ${self:custom.deployment_bucket}
  tags:
    account_name: ${self:custom.account_name}
    env: ${self:custom.env}
    project: ${self:custom.project}
    deploy_type: ${self:custom.deploy_type}

functions:
  buildpr:
    name: ${self:service}-build-pr-${self:custom.env}
    handler: src/build_pr.handler
    events:
      - http:
          path: buildpr
          method: post